stages:
  training:
    cmd: python pipelines/training_pipeline.py
    deps:
      - pipelines/training_pipeline.py
      - src/components/data_ingestion.py
      - src/components/data_preprocessor.py
      - src/components/data_transformation.py
      - src/components/build_model.py
      - src/components/model_trainer.py
      - src/utils/utils.py

    outs:
      - artifacts/tokenizer.json
      - artifacts/model.pkl

  prediction:
    cmd: python pipelines/prediction_pipeline.py
    deps:
      - src/pipelines/prediction_pipeline.py
      - src/components/model_prediction.py
      - src/utils/utils.py
      # Add other dependencies as needed
    
